dist: trusty
env:
  global:
  - secure: kc1CAz/HbH4i3RMcjXcmmj8D8navQB+8Qnq/4S5hPuBk2JtFSOt4dokbrRNboiohq/cGDMfBI02O8tS5jsqU0etOveXNBI7mAoNT9zvtEOG40I1QcVOwwuNFwFzyKkijQQUGC64R4x3bGAd2A0JUu2cOn/PEkWWFuudsOgaETgFGU8s7U+6eVHZYMiedD7Zn4rKYd1GdJITw2NLuQb6OtXwBn/Yo5bu3Ap8w8gbBEAThLDPRcOGqp5o03/FoGR4/kv37KLYkV+aETEJzaxBZHa9ZxTnpTKs1HCcdVejYMr2begS0BtB06eva6hZA16AFYpmc455gEaYHlaG7ih9qaWq917beJm2M6Wehmd+CyPXOX9xWyxZcCDcrgjq688dmQotXCad+0PcPBbhdK/tnXvpxN+5YczC3gqlYVATpqWrd7S/fLs1on5YNDJc8HJZwF2ACnZad9zVoXkTaB1Crk9DQDEfivREv5WLmbCdu8Uq35p2in79h0hSeynDHlp3VXhbj/R0TUf191pigTGwq3PxVFbLRaf6KQcsblYU3KuIPUHcICozeDkOkmTd7hxqGJOLs97j6e8byDqcNRMfL2NpqRw8qqvNffsHHrIU3ZvdTU06ae3dzEobGXiRcP4hSTS/Yfd7nt061lVssmTPf0MWqkf2oKBnxeeC3ra50oeI=
language: node_js
node_js:
- '8'
before_deploy:
- hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  repo: Android-MI/Android-MI.github.io
  local_dir: public
  target_branch: master
  fqdn: http://memmrf.top
  project_name: memmrf.me
  email: 372728569@qq.com

name: memmrf.me
